on:
  push:
    branches:
      - actions
      - develop
      - master
    paths-ignore:
      - "**/README.md"
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    runs-on: mono-runner
    timeout-minutes: 15

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          token: ${{ secrets.BUILDBOT_PERSONAL_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          ./gradlew build